[workspace]
members = [
    "abetterworld",
    "apps/desktop",
]
resolver = "2"

[workspace.dependencies]
wgpu = "24.0.1"
winit = { version = "0.29", features = ["android-native-activity"] }
console_error_panic_hook = "0.1.7"
console_log = "0.2"
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wasm-bindgen-futures = "0.4.34"
wasm-bindgen-test = "0.3"