[package]
name = "abetterworld"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
bytemuck = { version = "1.10", features = ["derive"] }
cgmath = "0.18"
wgpu = {workspace = true}
reqwest = { version = "0.11", features = ["json", "gzip", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2"
byteorder = "1.4"
image = "0.24"
bytes = "1"
dashmap = "5"
once_cell = "1"
urlencoding = "2"
sha2 = "0.10"
hex = "0.4"