/* Generated with cbindgen:0.29.0 */

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ABetterWorldiOS {
  uint8_t _private[0];
} ABetterWorldiOS;

struct ABetterWorldiOS *abetterworld_ios_new(void);

void abetterworld_ios_free(struct ABetterWorldiOS *ptr);

void abetterworld_ios_init(struct ABetterWorldiOS *ptr,
                           void *metal_device_raw,
                           void *metal_layer_raw,
                           double width,
                           double height);

void abetterworld_ios_resize(struct ABetterWorldiOS *ptr, double width, double height);

void abetterworld_ios_render(struct ABetterWorldiOS *ptr);

const char *abetterworld_ios_version(void);

void abetterworld_ios_gesture_pinch(struct ABetterWorldiOS *ptr,
                                    bool begin,
                                    double scale,
                                    double velocity);

void abetterworld_ios_gesture_pan_orbit(struct ABetterWorldiOS *ptr,
                                        bool begin,
                                        double dx,
                                        double dy,
                                        double vx,
                                        double vy);

void abetterworld_ios_gesture_pan_translate(struct ABetterWorldiOS *ptr,
                                            bool begin,
                                            double dx,
                                            double dy,
                                            double vx,
                                            double vy);

void abetterworld_ios_gesture_rotate(struct ABetterWorldiOS *ptr,
                                     bool begin,
                                     double radians,
                                     double velocity);

void abetterworld_ios_gesture_double_tap(struct ABetterWorldiOS *ptr, double x, double y);

void abetterworld_ios_touch_down(struct ABetterWorldiOS *ptr, bool active, double x, double y);
