/* Generated with cbindgen:0.29.0 */

/* Warning: This file is auto-generated by cbindgen. Do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct ABetterWorldiOS {
  uint8_t _private[0];
} ABetterWorldiOS;

struct ABetterWorldiOS *abetterworld_ios_new(void);

void abetterworld_ios_free(struct ABetterWorldiOS *ptr);

void abetterworld_ios_init(struct ABetterWorldiOS *ptr,
                           void *metal_device_raw,
                           void *metal_layer_raw,
                           double width,
                           double height);

void abetterworld_ios_resize(struct ABetterWorldiOS *ptr, double width, double height);

void abetterworld_ios_render(struct ABetterWorldiOS *ptr);

const char *abetterworld_ios_version(void);
